services:
  - type: web
    name: n8n-service
    env: docker
    repo: https://github.com/AdesGit/n8n-docker-setup.git
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: NGROK_AUTH_TOKEN
        value: your_ngrok_auth_token
    plan: free
    healthCheckPath: /
    buildCommand: docker build -t n8n-service .
    startCommand: docker run -e PORT=$PORT -p $PORT:$PORT n8n-service
