name: Deploy n8n

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # This will run the action every hour

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/n8n:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/n8n:latest

      - name: Deploy to Docker
        run: |
          # Ensure any existing container is stopped and removed
          docker stop n8n || true
          docker rm n8n || true

          # Create a volume for persistent data if it doesn't exist
          docker volume create n8n-data || true

          # Run the container with the volume attached
          docker run -d --name n8n -p 5678:5678 -v n8n-data:/home/node/.n8n ${{ secrets.DOCKER_USERNAME }}/n8n:latest

      - name: Check Docker container logs
        run: |
          sleep 10
          docker logs n8n
