name: Deploy n8n

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # This will run the action every hour

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ secrets.DOCKER_USERNAME }}/n8n:latest
          push: true

      - name: Deploy to Docker
        run: |
          docker run -d --name n8n -p 5678:5678 ${{ secrets.DOCKER_USERNAME }}/n8n:latest
