name: Deploy n8n

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # This will run the action every hour

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Updated to v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Updated to v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4  # Updated to v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/n8n:latest

      - name: Deploy to Docker
        run: |
          docker run -d --name n8n -p 5678:5678 ${{ secrets.DOCKER_USERNAME }}/n8n:latest

      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin
          
      - name: Run ngrok
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok http 5678 &

      - name: Get ngrok URL
        id: get-ngrok-url
        run: |
          sleep 5
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV

      - name: Output ngrok URL
        run: |
          echo "n8n is accessible at ${{ env.NGROK_URL }}"
